version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          command: |
            aws cloudformation delete-stack melisas-stack

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name melisas-stack --debug
          when: on_fail
      #- run: return 1
      - destroy_environment
        

workflows:
  my_workflow:
    jobs:
      - create_infrastructure
